name: Deploy-Backend

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'dev, prd'
        required: true
        type: choice
        options:
          - dev
          - prd
      service:
        description: 'backend'
        required: true
        type: choice
        options:
          - backend
  workflow_call:
    inputs:
      env:
        description: 'dev, prd'
        type: string
        required: true
      service:
        description: 'backend'
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  api-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Application Docker Deploy
        run: |
          cd ./packages/backend
          sh ./aws_deploy.sh build ${{ github.event.inputs.env }}
          sh ./aws_deploy.sh push ${{ github.event.inputs.env }}

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
